### ISSUE TITLE
Doesn't work if core isn't a dependency of the root package

### ISSUE THREAD

**Issue by danepowell** [zaporylie/composer-drupal-optimizations#12]
Some projects may not depend on Drupal core directly. Rather, they might depend on a distribution or automation tool like [Lightning](https://github.com/acquia/lightning) or [BLT](https://github.com/acquia/blt), which in turn depends on Drupal core (and optionally, composer-drupal-optimizations).

In these scenarios, composer-drupal-optimizations will have no effect, regardless of whether it is included by the upstream or downstream project.

It seems like either composer-drupal-optimizations should support running when Drupal core isn't a root-level dependency, or it should clearly document that having Drupal core as a root-level dependency is a requirement for use.

**Comment by zaporylie** [comment]
If `drupal/core` isn't defined as project-level dependency this package simply cannot say which legacy version of symfony can be safely removed.

Nevertheless, in that case you can still benefit from composer-drupal-optimizations and optimize composer runtime by passing optional configuration - check relevant section of the README file. 

Feel free to open a PR with documentation changes to README file which highlights mentioned scenario and course of action.

**Comment by danepowell** [comment]
It seems like you could poll all packages (`$composer->getRepositoryManager()->getLocalRepository()->getPackages()`) and determine the Drupal constraint based on that... but I agree that at least it wouldn't be trivial.

I'll work on a doc fix for now.

**Comment by zaporylie** [comment]
@danepowell I'll check that.
