### ISSUE TITLE
Support for Composer 2

### ISSUE THREAD

**Issue by danepowell** [zaporylie/composer-drupal-optimizations#16]
Composer 2 will be released soon, and plugins such as composer-drupal-optimizations need to be modified to support it: https://github.com/composer/composer/issues/8726

**Comment by danepowell** [comment]
Perhaps we should centralize discussion in #17, but note my comment there about performance: Composer 2 is so much more efficient than Composer 1 that you might not even need this plugin.

**Comment by Berdir** [comment]
I agree that it is very likely no longer required for composer 2. Maybe it could just do nothing if it detects composer v2? that would make it easier to keep it in project (templates) as not everyone will be able to switch to composer 2 at the same time, and by removing it, you'd expose the composer 1 users to the performance issues again.

**Comment by zaporylie** [comment]
@Berdir See #17 - I agree with you hence I return early from the Plugin if Composer 2 is detected.

**Comment by gitressa** [comment]
Perhaps something like this could be added to the [About](https://github.com/zaporylie/composer-drupal-optimizations/blob/master/README.md#about) section in the README file?

> This composer-plugin contains a set of improvements that makes running heavy duty composer commands (i.e. composer update or composer require) much faster.
> 
> Probably not needed for Composer 2, since it is quite fast by default.

Last line added ^^, which I have created a MR for: #26.
