### ISSUE TITLE
Maintain list of $lowestTags inside composer.json

### ISSUE THREAD

**Issue by tobybellwood** [zaporylie/composer-drupal-optimizations#3]
Following on from the comments on twitter - is there merit in using the same technique to exclude other versions via the composer.json (as opposed to hardcoded into $lowestTags in src/cache.php).  Being able to update the composer.json (e.g. as an 'Extra') may be a more versionable solution?

Thanks for the work!

**Comment by zaporylie** [comment]
Yep, I was planning to add this feature. Just have to find the best possible way of getting content of composer.json/extra into `Cache`.

My plan is to default to `symfony/symfony => v3.4`, and in case you want to override it via `composer.json/extra/lowest-tags` you must remember to add it manually there. From all test I did only `symfony/symfony` has a significant impact but, of course, I couldn't test it out in all possible applications.

**Comment by tobybellwood** [comment]
This may be a use case for https://github.com/cweagans/composer-configurable-plugin

Elsewise - you should be able to collect it from composer.json using $extra = $event->getComposer()->getPackage()->getExtra();

**Comment by zaporylie** [comment]
Yep, I am familiar with the concept 🙂 It is just that this package relies on Composer internals - https://github.com/composer/composer/blob/master/src/Composer/Repository/ComposerRepository.php and https://github.com/composer/composer/blob/master/src/Composer/Cache.php, which makes it so neat. Unfortunately, Cache doesn't provide access to Composer/Package object, neither is ComposerRepository. I try hard to avoid passing config via singleton what makes it a challenge.

**Comment by zaporylie** [comment]
Singleton approach can be found in #5

**Comment by zaporylie** [comment]
This is fixed via #5
